version: '3.8'

services:

  api:

    build:
      context: .
      dockerfile: Dockerfile

    image: sistemaspdb/china-api:latest

    ports:
      - "5000:80"

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Jwt__Key=${JWT_KEY}
      - ConnectionStrings__PostgreSql=Host=db;Port=5432;Database=china_venezuela;Username=postgres;Password=${POSTGRES_PASSWORD}

    depends_on:
      db:
        condition: service_healthy


  web:

    build:
      context: ./frontend
      dockerfile: Dockerfile

    image: sistemaspdb/china-web:latest

    ports:
      - "8080:80"

    depends_on:
      - api
  db:

    image: postgres:16-alpine

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d china_venezuela"]
      interval: 5s
      timeout: 5s
      retries: 20

    environment:
      POSTGRES_DB: china_venezuela
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:

  postgres-data: