// <auto-generated />
using System;
using ChinaVenezuela.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChinaVenezuela.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChinaVenezuelaDbContext))]
    [Migration("20260909212701_AgregarDetallesAtributoFicha")]
    partial class AgregarDetallesAtributoFicha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChinaVenezuela.Domain.Auditoria.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("accion");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<DateTimeOffset>("FechaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_utc");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_entidad");

                    b.Property<string>("ValoresAntesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("valores_antes_json");

                    b.Property<string>("ValoresDespuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("valores_despues_json");

                    b.HasKey("Id");

                    b.HasIndex("TipoEntidad", "EntidadId")
                        .HasDatabaseName("ix_registro_auditoria_tipo_entidad_entidad_id");

                    b.ToTable("registro_auditoria", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Catalogos.Aduana", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("aduana", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Catalogos.ContenedorCompartido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("contenedor_compartido", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Catalogos.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clasificacion")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("clasificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Rif")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rif");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("Rif")
                        .IsUnique()
                        .HasDatabaseName("ux_empresa_rif")
                        .HasFilter("rif IS NOT NULL");

                    b.ToTable("empresa", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Catalogos.MarcaBulto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("marca_bulto", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Catalogos.PuertoLlegada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("puerto_llegada", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.FichasTecnicas.AtributoFichaTecnica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Atributo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("atributo");

                    b.Property<string>("ColorParaFabricar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("color_para_fabricar");

                    b.Property<string>("ComposicionTela")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("composicion_tela");

                    b.Property<string>("CurvaTalla")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("curva_talla");

                    b.Property<Guid>("FichaTecnicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("ficha_tecnica_id");

                    b.Property<string>("MarcaProducto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca_producto");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacion");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("FichaTecnicaId", "Atributo")
                        .IsUnique();

                    b.ToTable("ficha_tecnica_atributo", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.FichasTecnicas.FichaTecnica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("categoria");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("codigo");

                    b.Property<string>("ColorParaFabricar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("color_para_fabricar");

                    b.Property<string>("ComposicionTela")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("composicion_tela");

                    b.Property<string>("CurvaTalla")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("curva_talla");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<byte[]>("ImagenDatos")
                        .HasColumnType("bytea")
                        .HasColumnName("imagen_datos");

                    b.Property<string>("ImagenTipoContenido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("imagen_tipo_contenido");

                    b.Property<string>("Linea")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("linea");

                    b.Property<string>("MarcaProducto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca_producto");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("ficha_tecnica", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Pedidos.AgentePedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("agente_pedido", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Pedidos.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreadoPorCodigoUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("creado_por_codigo_usuario");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Pedidos.PedidoGrupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<Guid>("ProductoPedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_pedido_id");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoPedidoId")
                        .IsUnique();

                    b.ToTable("pedidos_grupos", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Pedidos.ProductoPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Agente")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("agente");

                    b.Property<int?>("CantidadBulto")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_bulto");

                    b.Property<int?>("CantidadDoz")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_doz");

                    b.Property<int?>("CantidadUnidades")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_unidades");

                    b.Property<string>("CodigoBarraAsignado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_barra_asignado");

                    b.Property<string>("ColorParaFabricar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("color_para_fabricar");

                    b.Property<string>("ComposicionTela")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("composicion_tela");

                    b.Property<string>("CreadoPorCodigoUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("creado_por_codigo_usuario");

                    b.Property<string>("CurvaTalla")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("curva_talla");

                    b.Property<bool>("Enviado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("enviado");

                    b.Property<string>("Fabrica")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("fabrica");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateTimeOffset?>("FechaEnvioUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio_utc");

                    b.Property<DateOnly?>("FechaInicioFabricacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio_fabricacion");

                    b.Property<DateOnly>("FechaRegistroPedido")
                        .HasColumnType("date")
                        .HasColumnName("fecha_registro_pedido");

                    b.Property<string>("MarcaBulto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca_bulto");

                    b.Property<string>("MarcaProducto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca_producto");

                    b.Property<int?>("PackPorCaja")
                        .HasColumnType("integer")
                        .HasColumnName("pack_por_caja");

                    b.Property<decimal?>("PrecioRmb")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("precio_rmb");

                    b.Property<string>("ReferenciaAsignada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia_asignada");

                    b.Property<string>("TipoProducto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_producto");

                    b.Property<decimal?>("TotalRmb")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("total_rmb");

                    b.HasKey("Id");

                    b.HasIndex("CodigoBarraAsignado")
                        .IsUnique();

                    b.ToTable("producto_pedido", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Pedidos.ProductoPedidoBulto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("MarcaBultoId")
                        .HasColumnType("uuid")
                        .HasColumnName("marca_bulto_id");

                    b.Property<Guid>("ProductoPedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_pedido_id");

                    b.HasKey("Id");

                    b.HasIndex("MarcaBultoId");

                    b.HasIndex("ProductoPedidoId", "MarcaBultoId")
                        .IsUnique();

                    b.ToTable("producto_pedido_bulto", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Pedidos.ProductoPedidoImagen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClaveAlmacenamiento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("clave_almacenamiento");

                    b.Property<DateTimeOffset?>("FechaActualizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion_utc");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_original");

                    b.Property<Guid>("ProductoPedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("producto_pedido_id");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_contenido");

                    b.HasKey("Id");

                    b.HasIndex("ProductoPedidoId", "Tipo")
                        .IsUnique();

                    b.ToTable("producto_pedido_imagen", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Pedidos.RegistroPrecioPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoBarra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_barra");

                    b.Property<decimal>("PrecioSistema")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_sistema");

                    b.Property<decimal>("PrecioVerificado")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_verificado");

                    b.Property<string>("Producto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("producto");

                    b.Property<string>("Sucursal")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("sucursal");

                    b.HasKey("Id");

                    b.ToTable("registro_precio_pedido", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Recepciones.CompraRecibida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aduana")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aduana");

                    b.Property<string>("ClaveArchivoComprobante")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("clave_archivo_comprobante");

                    b.Property<Guid?>("ContenedorCompartidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contenedor_compartido_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset?>("FechaActualizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion_utc");

                    b.Property<DateTimeOffset?>("FechaCargaArchivoComprobanteUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_carga_archivo_comprobante_utc");

                    b.Property<DateTimeOffset?>("FechaComprobanteEnviadoUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_comprobante_enviado_utc");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateOnly?>("FechaLlegada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_llegada");

                    b.Property<DateOnly>("FechaSalida")
                        .HasColumnType("date")
                        .HasColumnName("fecha_salida");

                    b.Property<Guid?>("MarcaBultoId")
                        .HasColumnType("uuid")
                        .HasColumnName("marca_bulto_id");

                    b.Property<string>("NombreArchivoComprobante")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nombre_archivo_comprobante");

                    b.Property<string>("NombreContenedor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_contenedor");

                    b.Property<string>("NumeroContenedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_contenedor");

                    b.Property<string>("PuertoLlegada")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("puerto_llegada");

                    b.Property<string>("ReceptorCodigoUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("receptor_codigo_usuario");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("En proceso")
                        .HasColumnName("status");

                    b.Property<long?>("TamanoBytesArchivoComprobante")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes_archivo_comprobante");

                    b.Property<string>("TipoContenidoArchivoComprobante")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_contenido_archivo_comprobante");

                    b.HasKey("Id");

                    b.HasIndex("ContenedorCompartidoId")
                        .HasDatabaseName("ix_compra_recibida_contenedor_compartido_id");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_compra_recibida_empresa_id");

                    b.HasIndex("MarcaBultoId")
                        .HasDatabaseName("ix_compra_recibida_marca_bulto_id");

                    b.HasIndex("NumeroContenedor")
                        .HasDatabaseName("ix_compra_recibida_numero_contenedor");

                    b.HasIndex("ReceptorCodigoUsuario")
                        .HasDatabaseName("ix_compra_recibida_receptor_codigo_usuario");

                    b.ToTable("compra_recibida", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Usuarios.Grupo", b =>
                {
                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Nombre");

                    b.ToTable("grupo", (string)null);

                    b.HasData(
                        new
                        {
                            Nombre = "Prueba"
                        });
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Usuarios.GrupoUsuario", b =>
                {
                    b.Property<string>("CodigoUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_usuario");

                    b.Property<string>("NombreGrupo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_grupo");

                    b.HasKey("CodigoUsuario", "NombreGrupo");

                    b.ToTable("grupo_usuario", (string)null);

                    b.HasData(
                        new
                        {
                            CodigoUsuario = "MARTHA",
                            NombreGrupo = "Administradores"
                        });
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<string>("CodigoUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_usuario");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("Correo")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo");

                    b.Property<bool>("CorreoVerificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("correo_verificado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TokenVerificacionExpiraUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("token_verificacion_expira_utc");

                    b.Property<string>("TokenVerificacionHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_verificacion_hash");

                    b.HasKey("CodigoUsuario");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ux_usuario_correo")
                        .HasFilter("correo IS NOT NULL");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_usuario_nombre");

                    b.ToTable("usuario", (string)null);

                    b.HasData(
                        new
                        {
                            CodigoUsuario = "MARTHA",
                            ContrasenaHash = "PBKDF2-SHA256$600000$/ArqC9UVvmvFUXd6R3AnLw==$7LqpJF/sNGKbmYt60NGHe4RBjujsh04P8DkWFUvBVWI=",
                            CorreoVerificado = true,
                            Nombre = "Martha",
                            Status = true
                        });
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.FichasTecnicas.AtributoFichaTecnica", b =>
                {
                    b.HasOne("ChinaVenezuela.Domain.FichasTecnicas.FichaTecnica", "FichaTecnica")
                        .WithMany("Atributos")
                        .HasForeignKey("FichaTecnicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FichaTecnica");
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Pedidos.PedidoGrupo", b =>
                {
                    b.HasOne("ChinaVenezuela.Domain.Pedidos.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChinaVenezuela.Domain.Pedidos.ProductoPedido", null)
                        .WithOne("GrupoPedido")
                        .HasForeignKey("ChinaVenezuela.Domain.Pedidos.PedidoGrupo", "ProductoPedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Pedidos.ProductoPedidoBulto", b =>
                {
                    b.HasOne("ChinaVenezuela.Domain.Catalogos.MarcaBulto", "MarcaBulto")
                        .WithMany()
                        .HasForeignKey("MarcaBultoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChinaVenezuela.Domain.Pedidos.ProductoPedido", "ProductoPedido")
                        .WithMany("Bultos")
                        .HasForeignKey("ProductoPedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarcaBulto");

                    b.Navigation("ProductoPedido");
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Pedidos.ProductoPedidoImagen", b =>
                {
                    b.HasOne("ChinaVenezuela.Domain.Pedidos.ProductoPedido", null)
                        .WithMany("Imagenes")
                        .HasForeignKey("ProductoPedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Recepciones.CompraRecibida", b =>
                {
                    b.HasOne("ChinaVenezuela.Domain.Catalogos.ContenedorCompartido", "ContenedorCompartido")
                        .WithMany()
                        .HasForeignKey("ContenedorCompartidoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChinaVenezuela.Domain.Catalogos.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChinaVenezuela.Domain.Catalogos.MarcaBulto", "MarcaBulto")
                        .WithMany()
                        .HasForeignKey("MarcaBultoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChinaVenezuela.Domain.Usuarios.Usuario", "Receptor")
                        .WithMany()
                        .HasForeignKey("ReceptorCodigoUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContenedorCompartido");

                    b.Navigation("Empresa");

                    b.Navigation("MarcaBulto");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Usuarios.GrupoUsuario", b =>
                {
                    b.HasOne("ChinaVenezuela.Domain.Usuarios.Usuario", "Usuario")
                        .WithMany("Grupos")
                        .HasForeignKey("CodigoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.FichasTecnicas.FichaTecnica", b =>
                {
                    b.Navigation("Atributos");
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Pedidos.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Pedidos.ProductoPedido", b =>
                {
                    b.Navigation("Bultos");

                    b.Navigation("GrupoPedido");

                    b.Navigation("Imagenes");
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Usuarios.Usuario", b =>
                {
                    b.Navigation("Grupos");
                });
#pragma warning restore 612, 618
        }
    }
}
