// <auto-generated />
using System;
using ChinaVenezuela.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChinaVenezuela.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChinaVenezuelaDbContext))]
    [Migration("20260805160730_InitialCompraRecibida")]
    partial class InitialCompraRecibida
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChinaVenezuela.Domain.Auditoria.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("accion");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<DateTimeOffset>("FechaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_utc");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_entidad");

                    b.Property<string>("ValoresAntesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("valores_antes_json");

                    b.Property<string>("ValoresDespuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("valores_despues_json");

                    b.HasKey("Id");

                    b.HasIndex("TipoEntidad", "EntidadId")
                        .HasDatabaseName("ix_registro_auditoria_tipo_entidad_entidad_id");

                    b.ToTable("registro_auditoria", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Recepciones.CompraRecibida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aduana")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aduana");

                    b.Property<bool>("ContenedorCompartido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("contenedor_compartido");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("empresa");

                    b.Property<DateTimeOffset?>("FechaActualizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion_utc");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateOnly?>("FechaLlegada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_llegada");

                    b.Property<DateOnly>("FechaSalida")
                        .HasColumnType("date")
                        .HasColumnName("fecha_salida");

                    b.Property<string>("MarcaBultos")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("marca_bultos");

                    b.Property<string>("NombreContenedor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_contenedor");

                    b.Property<string>("NumeroContenedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_contenedor");

                    b.Property<string>("PuertoLlegada")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("puerto_llegada");

                    b.HasKey("Id");

                    b.HasIndex("NumeroContenedor")
                        .HasDatabaseName("ix_compra_recibida_numero_contenedor");

                    b.ToTable("compra_recibida", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
