// <auto-generated />
using System;
using ChinaVenezuela.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChinaVenezuela.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChinaVenezuelaDbContext))]
    partial class ChinaVenezuelaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChinaVenezuela.Domain.Auditoria.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("accion");

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidad_id");

                    b.Property<DateTimeOffset>("FechaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_utc");

                    b.Property<string>("TipoEntidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_entidad");

                    b.Property<string>("ValoresAntesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("valores_antes_json");

                    b.Property<string>("ValoresDespuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("valores_despues_json");

                    b.HasKey("Id");

                    b.HasIndex("TipoEntidad", "EntidadId")
                        .HasDatabaseName("ix_registro_auditoria_tipo_entidad_entidad_id");

                    b.ToTable("registro_auditoria", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Catalogos.Aduana", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("aduana", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Catalogos.ContenedorCompartido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("contenedor_compartido", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Catalogos.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Clasificacion")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("clasificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Rif")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rif");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("Rif")
                        .IsUnique()
                        .HasDatabaseName("ux_empresa_rif")
                        .HasFilter("rif IS NOT NULL");

                    b.ToTable("empresa", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Catalogos.MarcaBulto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("marca_bulto", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Catalogos.PuertoLlegada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("puerto_llegada", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Recepciones.CompraRecibida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aduana")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aduana");

                    b.Property<Guid?>("ContenedorCompartidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contenedor_compartido_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descripcion");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateTimeOffset?>("FechaActualizacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion_utc");

                    b.Property<DateTimeOffset>("FechaCreacionUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion_utc");

                    b.Property<DateOnly?>("FechaLlegada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_llegada");

                    b.Property<DateOnly>("FechaSalida")
                        .HasColumnType("date")
                        .HasColumnName("fecha_salida");

                    b.Property<Guid?>("MarcaBultoId")
                        .HasColumnType("uuid")
                        .HasColumnName("marca_bulto_id");

                    b.Property<string>("NombreContenedor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_contenedor");

                    b.Property<string>("NumeroContenedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_contenedor");

                    b.Property<string>("PuertoLlegada")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("puerto_llegada");

                    b.Property<string>("ReceptorCodigoUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("receptor_codigo_usuario");

                    b.HasKey("Id");

                    b.HasIndex("ContenedorCompartidoId")
                        .HasDatabaseName("ix_compra_recibida_contenedor_compartido_id");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_compra_recibida_empresa_id");

                    b.HasIndex("MarcaBultoId")
                        .HasDatabaseName("ix_compra_recibida_marca_bulto_id");

                    b.HasIndex("NumeroContenedor")
                        .HasDatabaseName("ix_compra_recibida_numero_contenedor");

                    b.HasIndex("ReceptorCodigoUsuario")
                        .HasDatabaseName("ix_compra_recibida_receptor_codigo_usuario");

                    b.ToTable("compra_recibida", (string)null);
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Usuarios.Grupo", b =>
                {
                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Nombre");

                    b.ToTable("grupo", (string)null);

                    b.HasData(
                        new
                        {
                            Nombre = "Prueba"
                        });
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Usuarios.GrupoUsuario", b =>
                {
                    b.Property<string>("CodigoUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_usuario");

                    b.Property<string>("NombreGrupo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_grupo");

                    b.HasKey("CodigoUsuario", "NombreGrupo");

                    b.ToTable("grupo_usuario", (string)null);

                    b.HasData(
                        new
                        {
                            CodigoUsuario = "MARTHA",
                            NombreGrupo = "Administradores"
                        });
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<string>("CodigoUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_usuario");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("Correo")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.HasKey("CodigoUsuario");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ux_usuario_correo")
                        .HasFilter("correo IS NOT NULL");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_usuario_nombre");

                    b.ToTable("usuario", (string)null);

                    b.HasData(
                        new
                        {
                            CodigoUsuario = "MARTHA",
                            ContrasenaHash = "PBKDF2-SHA256$600000$/ArqC9UVvmvFUXd6R3AnLw==$7LqpJF/sNGKbmYt60NGHe4RBjujsh04P8DkWFUvBVWI=",
                            Nombre = "Martha",
                            Status = true
                        });
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Recepciones.CompraRecibida", b =>
                {
                    b.HasOne("ChinaVenezuela.Domain.Catalogos.ContenedorCompartido", "ContenedorCompartido")
                        .WithMany()
                        .HasForeignKey("ContenedorCompartidoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChinaVenezuela.Domain.Catalogos.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChinaVenezuela.Domain.Catalogos.MarcaBulto", "MarcaBulto")
                        .WithMany()
                        .HasForeignKey("MarcaBultoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChinaVenezuela.Domain.Usuarios.Usuario", "Receptor")
                        .WithMany()
                        .HasForeignKey("ReceptorCodigoUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ContenedorCompartido");

                    b.Navigation("Empresa");

                    b.Navigation("MarcaBulto");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Usuarios.GrupoUsuario", b =>
                {
                    b.HasOne("ChinaVenezuela.Domain.Usuarios.Usuario", "Usuario")
                        .WithMany("Grupos")
                        .HasForeignKey("CodigoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ChinaVenezuela.Domain.Usuarios.Usuario", b =>
                {
                    b.Navigation("Grupos");
                });
#pragma warning restore 612, 618
        }
    }
}
